## Logging Config

LOG_DIR = 'logs'
LOG_FILE = 'traffic.logs'

## City Signals
CITY_SIGNAL_TRAFFIC_LIMIT = 20
CITY_LOW_GREEN_TIME = 30
CITY_HIGH_GREEN_TIME = 60


## HighWay Signals
HIGHWAY_SIGNAL_TRAFFIC_LIMIT = 30
HIGHWAY_LOW_GREEN_TIME = 40
HIGHWAY_HIGH_GREEN_TIME = 80


# ## Town Signals
# TOWN_SIGNAL_TRAFFIC_LIMIT = 20
# TOWN_LOW_GREEN_TIME = 30
# TOWN_HIGH_GREEN_TIME = 60